--
-- PostgreSQL database dump
--

-- Dumped from database version 11.0
-- Dumped by pg_dump version 11.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE elections (
    id SERIAL PRIMARY KEY,
    name character varying(64),
    type character varying(8),
    date date
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX elections_pkey ON elections(id int4_ops);
CREATE INDEX elections_type_idx ON elections(type text_ops);

-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE places (
    id character varying(9) PRIMARY KEY,
    name character varying(64) NOT NULL,
    type character varying(8) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX places_pkey ON places(id text_ops);
CREATE INDEX places_type_idx ON places(type text_ops);

-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE results (
    id SERIAL PRIMARY KEY,
    election_id integer REFERENCES elections(id) ON DELETE RESTRICT,
    place_id character varying(9) REFERENCES places(id) ON DELETE RESTRICT,
    party character varying(64),
    first_name character varying(128),
    surname character varying(64),
    votes integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX results_pkey ON results(id int4_ops);
